version: '3.8'

services:
  rag-pdf-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - API_KEY=${API_KEY:-your-secret-api-key}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./embeddings:/app/embeddings
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
